"""Adiciona coluna das rotas

Revision ID: 414bcba625b5
Revises: 
Create Date: 2025-10-19 22:46:29.675978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414bcba625b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rota', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.drop_column('rota')

    # ### end Alembic commands ###
